import { readFile, copyFile, readdir, stat } from "node:fs/promises";
import { join, basename, extname, relative, sep } from "node:path";
import { config } from "../config.js";
import { ValidationError, ModelError } from "../utils/errors.js";
import { logger } from "../utils/logger.js";
import { resolveOutputDir, resolveInputDir } from "./output-dir.js";

/**
 * Resolve ComfyUI's REAL input directory (honors a custom --input-directory /
 * --base-directory). Used only for genuine local filesystem copies; HTTP uploads
 * go through the server API and don't need a path.
 */
async function getInputDir(): Promise<string> {
  return resolveInputDir();
}

/**
 * Copy a local image file into ComfyUI's input/ directory so it can be
 * referenced by LoadImage nodes in workflows.
 */
export async function uploadImage(
  sourcePath: string,
  filename?: string,
): Promise<{ filename: string; path: string }> {
  const inputDir = await getInputDir();
  const resolvedFilename = filename ?? basename(sourcePath);

  // Validate extension
  const ext = extname(resolvedFilename).toLowerCase();
  const allowed = [".png", ".jpg", ".jpeg", ".webp", ".bmp", ".gif", ".tiff", ".tif"];
  if (!allowed.includes(ext)) {
    throw new ValidationError(
      `Unsupported image format "${ext}". Supported: ${allowed.join(", ")}`,
    );
  }

  const targetPath = join(inputDir, resolvedFilename);
  logger.info("Uploading image to ComfyUI input", { sourcePath, targetPath });

  try {
    await copyFile(sourcePath, targetPath);
  } catch (err) {
    throw new ValidationError(
      `Failed to copy image: ${err instanceof Error ? err.message : err}`,
    );
  }

  return { filename: resolvedFilename, path: targetPath };
}

/**
 * Extract embedded workflow JSON from a ComfyUI-generated PNG file.
 * ComfyUI stores workflow data in PNG tEXt chunks under the keys
 * "prompt" (API format) and "workflow" (UI format).
 */
export async function extractWorkflowFromImage(
  imagePath: string,
): Promise<{ prompt?: Record<string, unknown>; workflow?: Record<string, unknown> }> {
  const ext = extname(imagePath).toLowerCase();
  if (ext !== ".png") {
    throw new ValidationError(
      "Workflow extraction only works with PNG files. ComfyUI embeds metadata in PNG tEXt chunks.",
    );
  }

  const buffer = await readFile(imagePath);
  const result: { prompt?: Record<string, unknown>; workflow?: Record<string, unknown> } = {};

  // Parse PNG chunks to find tEXt/iTXt chunks with "prompt" or "workflow" keys
  const chunks = parsePngTextChunks(buffer);

  for (const { keyword, text } of chunks) {
    if (keyword === "prompt") {
      try {
        result.prompt = JSON.parse(text);
      } catch {
        logger.warn("Failed to parse 'prompt' PNG metadata as JSON");
      }
    } else if (keyword === "workflow") {
      try {
        result.workflow = JSON.parse(text);
      } catch {
        logger.warn("Failed to parse 'workflow' PNG metadata as JSON");
      }
    }
  }

  if (!result.prompt && !result.workflow) {
    throw new ValidationError(
      "No ComfyUI workflow metadata found in this PNG. The image may not have been generated by ComfyUI, or metadata embedding may have been disabled.",
    );
  }

  return result;
}

interface PngTextChunk {
  keyword: string;
  text: string;
}

/**
 * Low-level PNG tEXt/iTXt chunk parser.
 * PNG format: 8-byte signature, then chunks of [4-byte length][4-byte type][data][4-byte CRC].
 */
function parsePngTextChunks(buffer: Buffer): PngTextChunk[] {
  const results: PngTextChunk[] = [];

  // Verify PNG signature
  const PNG_SIG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (buffer.length < 8 || !buffer.subarray(0, 8).equals(PNG_SIG)) {
    throw new ValidationError("Not a valid PNG file");
  }

  let offset = 8; // Skip signature

  while (offset + 8 <= buffer.length) {
    const chunkLength = buffer.readUInt32BE(offset);
    const chunkType = buffer.subarray(offset + 4, offset + 8).toString("ascii");
    const dataStart = offset + 8;
    const dataEnd = dataStart + chunkLength;

    if (dataEnd > buffer.length) break;

    if (chunkType === "tEXt") {
      // tEXt: keyword\0text
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString("latin1");
        const text = data.subarray(nullIdx + 1).toString("latin1");
        results.push({ keyword, text });
      }
    } else if (chunkType === "iTXt") {
      // iTXt: keyword\0compressionFlag\0compressionMethod\0languageTag\0translatedKeyword\0text
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString("utf-8");
        const compressionFlag = data[nullIdx + 1];
        // Skip compression method (1 byte), language tag, translated keyword
        let textStart = nullIdx + 3; // past null, compressionFlag, compressionMethod
        // Skip language tag (null-terminated)
        const langEnd = data.indexOf(0, textStart);
        if (langEnd >= 0) {
          textStart = langEnd + 1;
          // Skip translated keyword (null-terminated)
          const transEnd = data.indexOf(0, textStart);
          if (transEnd >= 0) {
            textStart = transEnd + 1;
          }
        }
        const textData = data.subarray(textStart);
        if (compressionFlag === 0) {
          results.push({ keyword, text: textData.toString("utf-8") });
        }
        // We skip compressed iTXt chunks — ComfyUI typically uses uncompressed
      }
    }

    if (chunkType === "IEND") break;

    // Next chunk: length(4) + type(4) + data(chunkLength) + CRC(4)
    offset = dataEnd + 4;
  }

  return results;
}

export interface OutputImage {
  filename: string;
  path: string;
  size: number;
  modified: string;
  /** Subfolder relative to the output dir ("" for top level), forward-slash
   *  normalized. ComfyUI writes to subfolders when a node's filename_prefix
   *  contains a path (e.g. SaveVideo "video/clip" → output/video/clip_00001.mp4).
   *  Pass { filename, subfolder } to get_image / stage_output_as_input. */
  subfolder: string;
  /** Media kind derived from the file extension. */
  kind: "image" | "video";
}

// Still-image extensions.
const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".bmp"]);
// Video / animation extensions written by VHS_VideoCombine, LTX, WAN, etc.
// NOTE: .webp and .gif can be still OR animated; ComfyUI's video nodes emit
// them as animations, so they're classified as "video" here.
const VIDEO_EXTS = new Set([".mp4", ".webm", ".mov", ".mkv", ".m4v", ".avi", ".gif", ".webp"]);
// Everything we list (images + videos/animations).
const MEDIA_EXTS = new Set([...IMAGE_EXTS, ...VIDEO_EXTS]);

function mediaKind(ext: string): "image" | "video" {
  return VIDEO_EXTS.has(ext) ? "video" : "image";
}

/**
 * List image AND video/animation files in the ComfyUI output directory.
 *
 * Covers VHS_VideoCombine / LTX / WAN video outputs (.mp4, .webm, …) in addition
 * to still images, because ComfyUI's /history often does NOT register VHS-style
 * video outputs — so a filesystem scan is the reliable way to confirm a finished
 * video render.
 */
export async function listOutputImages(options?: {
  limit?: number;
  pattern?: string;
}): Promise<OutputImage[]> {
  const outputDir = await resolveOutputDir();
  const limit = options?.limit ?? 20;
  const pattern = options?.pattern?.toLowerCase();

  // RECURSIVE scan: ComfyUI writes to subfolders when a node's filename_prefix
  // contains a path (SaveVideo / VHS / "video/clip" → output/video/clip_00001.mp4).
  // A flat readdir of the top level silently misses those — so a finished video can
  // look "not found" even though the dir resolved correctly. Walk the whole tree.
  let dirents;
  try {
    dirents = await readdir(outputDir, { recursive: true, withFileTypes: true });
  } catch {
    return [];
  }

  const images: OutputImage[] = [];

  for (const dirent of dirents) {
    if (!dirent.isFile()) continue;
    const ext = extname(dirent.name).toLowerCase();
    if (!MEDIA_EXTS.has(ext)) continue;

    // Dirent.parentPath (Node ≥20.12) is the absolute dir holding the entry.
    const parent = dirent.parentPath ?? outputDir;
    const subfolder = relative(outputDir, parent).split(sep).join("/"); // "" at top level
    const relPath = subfolder ? `${subfolder}/${dirent.name}` : dirent.name;
    // Match the pattern against the subfolder-relative path so "video/clip" works.
    if (pattern && !relPath.toLowerCase().includes(pattern)) continue;

    const filePath = join(parent, dirent.name);
    try {
      const info = await stat(filePath);
      images.push({
        filename: dirent.name,
        path: filePath,
        size: info.size,
        modified: info.mtime.toISOString(),
        subfolder,
        kind: mediaKind(ext),
      });
    } catch {
      continue;
    }
  }

  // Sort newest first
  images.sort((a, b) => b.modified.localeCompare(a.modified));

  return images.slice(0, limit);
}

import { fetchImage, uploadImageHttp } from "../comfyui/client.js";
import { readFile as nodeReadFile } from "node:fs/promises";

/**
 * Fetch a generated image from ComfyUI via HTTP /view endpoint.
 * Does NOT require COMFYUI_PATH — works with remote ComfyUI instances.
 */
export async function getOutputImage(
  filename: string,
  type: "output" | "input" | "temp" = "output",
  subfolder = "",
): Promise<{ base64: string; mimeType: string; filename: string }> {
  const result = await fetchImage(filename, type, subfolder);
  return { ...result, filename };
}

/**
 * Upload a local image to ComfyUI via HTTP multipart POST.
 * Falls back to HTTP when COMFYUI_PATH is not available (remote ComfyUI).
 */
export async function uploadImageAuto(
  sourcePath: string,
  filename?: string,
): Promise<{ filename: string }> {
  const resolvedFilename = filename ?? basename(sourcePath);
  const ext = extname(resolvedFilename).toLowerCase();
  if (!(ext in IMAGE_MIME)) {
    throw new ValidationError(
      `Unsupported image format "${ext}". Supported: ${Object.keys(IMAGE_MIME).join(", ")}`,
    );
  }
  const data = await nodeReadFile(sourcePath);
  const mimeType = IMAGE_MIME[ext] ?? "application/octet-stream";
  logger.info("Uploading image to ComfyUI via HTTP", { sourcePath, resolvedFilename });
  const result = await uploadImageHttp(resolvedFilename, data, mimeType);
  return { filename: result.name };
}

// ---------------------------------------------------------------------------
// Video / audio upload — mirrors upload_image. ComfyUI's /upload/image endpoint
// (and the input/ directory) accept arbitrary media, which video/audio loader
// nodes (e.g. VHS_LoadVideo, LoadAudio) then read by filename.
// ---------------------------------------------------------------------------

const IMAGE_MIME: Record<string, string> = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".bmp": "image/bmp",
  ".gif": "image/gif",
  ".tiff": "image/tiff",
  ".tif": "image/tiff",
};

const VIDEO_MIME: Record<string, string> = {
  ".mp4": "video/mp4",
  ".mov": "video/quicktime",
  ".webm": "video/webm",
  ".avi": "video/x-msvideo",
  ".mkv": "video/x-matroska",
  ".m4v": "video/x-m4v",
};

const AUDIO_MIME: Record<string, string> = {
  ".wav": "audio/wav",
  ".mp3": "audio/mpeg",
  ".flac": "audio/flac",
  ".ogg": "audio/ogg",
  ".m4a": "audio/mp4",
  ".aac": "audio/aac",
};

function resolveMediaMime(
  filename: string,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): string {
  const ext = extname(filename).toLowerCase();
  const mime = mimeMap[ext];
  if (!mime) {
    throw new ValidationError(
      `Unsupported ${kind} format "${ext}". Supported: ${Object.keys(mimeMap).join(", ")}`,
    );
  }
  return mime;
}

/** HTTP multipart upload of a media file to ComfyUI's input/ (works remotely). */
async function uploadMediaHttp(
  sourcePath: string,
  filename: string | undefined,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): Promise<{ filename: string }> {
  const resolvedFilename = filename ?? basename(sourcePath);
  const mimeType = resolveMediaMime(resolvedFilename, mimeMap, kind);
  const data = await nodeReadFile(sourcePath);
  logger.info(`Uploading ${kind} to ComfyUI via HTTP`, { sourcePath, resolvedFilename });
  const result = await uploadImageHttp(resolvedFilename, data, mimeType);
  return { filename: result.name };
}

/** Local filesystem copy of a media file into ComfyUI's input/ (needs COMFYUI_PATH). */
async function uploadMediaLocal(
  sourcePath: string,
  filename: string | undefined,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): Promise<{ filename: string; path: string }> {
  const inputDir = await getInputDir();
  const resolvedFilename = filename ?? basename(sourcePath);
  resolveMediaMime(resolvedFilename, mimeMap, kind);
  const targetPath = join(inputDir, resolvedFilename);
  logger.info(`Uploading ${kind} to ComfyUI input`, { sourcePath, targetPath });
  try {
    await copyFile(sourcePath, targetPath);
  } catch (err) {
    throw new ValidationError(
      `Failed to copy ${kind}: ${err instanceof Error ? err.message : err}`,
    );
  }
  return { filename: resolvedFilename, path: targetPath };
}

export const uploadVideoAuto = (sourcePath: string, filename?: string) =>
  uploadMediaHttp(sourcePath, filename, VIDEO_MIME, "video");
export const uploadVideoLocal = (sourcePath: string, filename?: string) =>
  uploadMediaLocal(sourcePath, filename, VIDEO_MIME, "video");
export const uploadAudioAuto = (sourcePath: string, filename?: string) =>
  uploadMediaHttp(sourcePath, filename, AUDIO_MIME, "audio");
export const uploadAudioLocal = (sourcePath: string, filename?: string) =>
  uploadMediaLocal(sourcePath, filename, AUDIO_MIME, "audio");

// ---------------------------------------------------------------------------
// stage_output_as_input — pipe one pipeline stage's OUTPUT into the next stage's
// loader (LoadImage / VHS_LoadVideo / LoadAudio) the CORRECT way: fetch the bytes
// from the ComfyUI server (/view) and re-register them as an INPUT via the same
// /upload/image endpoint the upload_* tools use. Because both legs go through the
// server API, this works even when ComfyUI was launched with a CUSTOM
// --input-directory / --output-directory — unlike copying or guessing a
// filesystem input/ path, which the server then rejects ("Invalid image file").
// ---------------------------------------------------------------------------

export type MediaKind = "image" | "video" | "audio";

const MIME_BY_KIND: Record<MediaKind, Record<string, string>> = {
  image: IMAGE_MIME,
  video: VIDEO_MIME,
  audio: AUDIO_MIME,
};

/** Infer image/video/audio from a filename's extension. */
export function inferMediaKind(filename: string): MediaKind {
  const ext = extname(filename).toLowerCase();
  if (ext in IMAGE_MIME) return "image";
  if (ext in VIDEO_MIME) return "video";
  if (ext in AUDIO_MIME) return "audio";
  throw new ValidationError(
    `Cannot infer media kind from extension "${ext}". ` +
      `Pass an explicit kind ("image" | "video" | "audio").`,
  );
}

/** Resolve the upload MIME type for a filename within a given media kind. */
function mimeForKind(filename: string, kind: MediaKind): string {
  const ext = extname(filename).toLowerCase();
  const mime = MIME_BY_KIND[kind][ext];
  if (!mime) {
    throw new ValidationError(
      `Extension "${ext}" is not a supported ${kind} format. ` +
        `Supported: ${Object.keys(MIME_BY_KIND[kind]).join(", ")}`,
    );
  }
  return mime;
}

export interface StageOutputAsInputArgs {
  /** Filename of the existing output/temp asset (from get_history / list_output_images). */
  filename: string;
  /** Subfolder the asset lives in, if any. */
  subfolder?: string;
  /** Source directory the asset currently lives in. "output" (default) or "temp" (previews). */
  type?: "output" | "temp";
  /** Force the media kind instead of inferring from the extension. */
  kind?: MediaKind;
  /** Override the filename it is registered under in the input/ directory. */
  asFilename?: string;
}

export interface StagedInput {
  /** Filename to drop into the loader's image/video/audio widget. */
  filename: string;
  /** Subfolder ComfyUI stored it under (usually ""). */
  subfolder: string;
  /** ComfyUI directory it now lives in (always "input"). */
  type: string;
  /** Detected/forced media kind. */
  kind: MediaKind;
}

/**
 * Stage an EXISTING ComfyUI output (or temp preview) as an INPUT, ready to feed
 * into the next stage's LoadImage / VHS_LoadVideo / LoadAudio loader.
 *
 * Fetches the bytes from the server via /view (the same path get_image uses) and
 * re-registers them as an input via /upload/image (the same path upload_image /
 * upload_video / upload_audio use). Goes entirely through the server API, so it
 * is correct even when ComfyUI runs with a custom input/output directory.
 */
export async function stageOutputAsInput(
  args: StageOutputAsInputArgs,
): Promise<StagedInput> {
  const sourceType = args.type ?? "output";
  const kind = args.kind ?? inferMediaKind(args.filename);
  const targetName = args.asFilename ?? basename(args.filename);
  const mimeType = mimeForKind(targetName, kind);

  // Fetch the existing asset's bytes via the same /view mechanism the asset
  // tools use (fetchImage handles cloud vs local). Despite the name, /view
  // returns raw bytes for any media type, not just images.
  const { base64 } = await fetchImage(
    args.filename,
    sourceType,
    args.subfolder ?? "",
  );
  const data = Buffer.from(base64, "base64");

  logger.info("Staging ComfyUI output as input via server API", {
    source: args.filename,
    sourceType,
    kind,
    targetName,
  });

  const result = await uploadImageHttp(targetName, data, mimeType);
  return {
    filename: result.name,
    subfolder: result.subfolder,
    type: result.type,
    kind,
  };
}
