import { readFile, copyFile, readdir, stat } from "node:fs/promises";
import { join, basename, extname } from "node:path";
import { config } from "../config.js";
import { ValidationError, ModelError } from "../utils/errors.js";
import { logger } from "../utils/logger.js";
import { resolveOutputDir } from "./output-dir.js";

function getInputDir(): string {
  if (!config.comfyuiPath) {
    throw new ValidationError(
      "COMFYUI_PATH is not configured. Set the COMFYUI_PATH environment variable.",
    );
  }
  return join(config.comfyuiPath, "input");
}

/**
 * Copy a local image file into ComfyUI's input/ directory so it can be
 * referenced by LoadImage nodes in workflows.
 */
export async function uploadImage(
  sourcePath: string,
  filename?: string,
): Promise<{ filename: string; path: string }> {
  const inputDir = getInputDir();
  const resolvedFilename = filename ?? basename(sourcePath);

  // Validate extension
  const ext = extname(resolvedFilename).toLowerCase();
  const allowed = [".png", ".jpg", ".jpeg", ".webp", ".bmp", ".gif", ".tiff", ".tif"];
  if (!allowed.includes(ext)) {
    throw new ValidationError(
      `Unsupported image format "${ext}". Supported: ${allowed.join(", ")}`,
    );
  }

  const targetPath = join(inputDir, resolvedFilename);
  logger.info("Uploading image to ComfyUI input", { sourcePath, targetPath });

  try {
    await copyFile(sourcePath, targetPath);
  } catch (err) {
    throw new ValidationError(
      `Failed to copy image: ${err instanceof Error ? err.message : err}`,
    );
  }

  return { filename: resolvedFilename, path: targetPath };
}

/**
 * Extract embedded workflow JSON from a ComfyUI-generated PNG file.
 * ComfyUI stores workflow data in PNG tEXt chunks under the keys
 * "prompt" (API format) and "workflow" (UI format).
 */
export async function extractWorkflowFromImage(
  imagePath: string,
): Promise<{ prompt?: Record<string, unknown>; workflow?: Record<string, unknown> }> {
  const ext = extname(imagePath).toLowerCase();
  if (ext !== ".png") {
    throw new ValidationError(
      "Workflow extraction only works with PNG files. ComfyUI embeds metadata in PNG tEXt chunks.",
    );
  }

  const buffer = await readFile(imagePath);
  const result: { prompt?: Record<string, unknown>; workflow?: Record<string, unknown> } = {};

  // Parse PNG chunks to find tEXt/iTXt chunks with "prompt" or "workflow" keys
  const chunks = parsePngTextChunks(buffer);

  for (const { keyword, text } of chunks) {
    if (keyword === "prompt") {
      try {
        result.prompt = JSON.parse(text);
      } catch {
        logger.warn("Failed to parse 'prompt' PNG metadata as JSON");
      }
    } else if (keyword === "workflow") {
      try {
        result.workflow = JSON.parse(text);
      } catch {
        logger.warn("Failed to parse 'workflow' PNG metadata as JSON");
      }
    }
  }

  if (!result.prompt && !result.workflow) {
    throw new ValidationError(
      "No ComfyUI workflow metadata found in this PNG. The image may not have been generated by ComfyUI, or metadata embedding may have been disabled.",
    );
  }

  return result;
}

interface PngTextChunk {
  keyword: string;
  text: string;
}

/**
 * Low-level PNG tEXt/iTXt chunk parser.
 * PNG format: 8-byte signature, then chunks of [4-byte length][4-byte type][data][4-byte CRC].
 */
function parsePngTextChunks(buffer: Buffer): PngTextChunk[] {
  const results: PngTextChunk[] = [];

  // Verify PNG signature
  const PNG_SIG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (buffer.length < 8 || !buffer.subarray(0, 8).equals(PNG_SIG)) {
    throw new ValidationError("Not a valid PNG file");
  }

  let offset = 8; // Skip signature

  while (offset + 8 <= buffer.length) {
    const chunkLength = buffer.readUInt32BE(offset);
    const chunkType = buffer.subarray(offset + 4, offset + 8).toString("ascii");
    const dataStart = offset + 8;
    const dataEnd = dataStart + chunkLength;

    if (dataEnd > buffer.length) break;

    if (chunkType === "tEXt") {
      // tEXt: keyword\0text
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString("latin1");
        const text = data.subarray(nullIdx + 1).toString("latin1");
        results.push({ keyword, text });
      }
    } else if (chunkType === "iTXt") {
      // iTXt: keyword\0compressionFlag\0compressionMethod\0languageTag\0translatedKeyword\0text
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString("utf-8");
        const compressionFlag = data[nullIdx + 1];
        // Skip compression method (1 byte), language tag, translated keyword
        let textStart = nullIdx + 3; // past null, compressionFlag, compressionMethod
        // Skip language tag (null-terminated)
        const langEnd = data.indexOf(0, textStart);
        if (langEnd >= 0) {
          textStart = langEnd + 1;
          // Skip translated keyword (null-terminated)
          const transEnd = data.indexOf(0, textStart);
          if (transEnd >= 0) {
            textStart = transEnd + 1;
          }
        }
        const textData = data.subarray(textStart);
        if (compressionFlag === 0) {
          results.push({ keyword, text: textData.toString("utf-8") });
        }
        // We skip compressed iTXt chunks — ComfyUI typically uses uncompressed
      }
    }

    if (chunkType === "IEND") break;

    // Next chunk: length(4) + type(4) + data(chunkLength) + CRC(4)
    offset = dataEnd + 4;
  }

  return results;
}

export interface OutputImage {
  filename: string;
  path: string;
  size: number;
  modified: string;
}

/**
 * List images in the ComfyUI output directory.
 */
export async function listOutputImages(options?: {
  limit?: number;
  pattern?: string;
}): Promise<OutputImage[]> {
  const outputDir = await resolveOutputDir();
  const limit = options?.limit ?? 20;
  const pattern = options?.pattern?.toLowerCase();

  let entries: string[];
  try {
    entries = await readdir(outputDir);
  } catch {
    return [];
  }

  const imageExts = new Set([".png", ".jpg", ".jpeg", ".webp"]);
  const images: OutputImage[] = [];

  for (const entry of entries) {
    const ext = extname(entry).toLowerCase();
    if (!imageExts.has(ext)) continue;
    if (pattern && !entry.toLowerCase().includes(pattern)) continue;

    const filePath = join(outputDir, entry);
    try {
      const info = await stat(filePath);
      if (!info.isFile()) continue;
      images.push({
        filename: entry,
        path: filePath,
        size: info.size,
        modified: info.mtime.toISOString(),
      });
    } catch {
      continue;
    }
  }

  // Sort newest first
  images.sort((a, b) => b.modified.localeCompare(a.modified));

  return images.slice(0, limit);
}

import { fetchImage, uploadImageHttp } from "../comfyui/client.js";
import { readFile as nodeReadFile } from "node:fs/promises";

/**
 * Fetch a generated image from ComfyUI via HTTP /view endpoint.
 * Does NOT require COMFYUI_PATH — works with remote ComfyUI instances.
 */
export async function getOutputImage(
  filename: string,
  type: "output" | "input" | "temp" = "output",
  subfolder = "",
): Promise<{ base64: string; mimeType: string; filename: string }> {
  const result = await fetchImage(filename, type, subfolder);
  return { ...result, filename };
}

/**
 * Upload a local image to ComfyUI via HTTP multipart POST.
 * Falls back to HTTP when COMFYUI_PATH is not available (remote ComfyUI).
 */
export async function uploadImageAuto(
  sourcePath: string,
  filename?: string,
): Promise<{ filename: string }> {
  const resolvedFilename = filename ?? basename(sourcePath);
  const ext = extname(resolvedFilename).toLowerCase();
  const allowed = [".png", ".jpg", ".jpeg", ".webp", ".bmp", ".gif", ".tiff", ".tif"];
  if (!allowed.includes(ext)) {
    throw new ValidationError(
      `Unsupported image format "${ext}". Supported: ${allowed.join(", ")}`,
    );
  }
  const data = await nodeReadFile(sourcePath);
  const mimeMap: Record<string, string> = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".webp": "image/webp", ".bmp": "image/bmp", ".gif": "image/gif",
    ".tiff": "image/tiff", ".tif": "image/tiff",
  };
  const mimeType = mimeMap[ext] ?? "application/octet-stream";
  logger.info("Uploading image to ComfyUI via HTTP", { sourcePath, resolvedFilename });
  const result = await uploadImageHttp(resolvedFilename, data, mimeType);
  return { filename: result.name };
}

// ---------------------------------------------------------------------------
// Video / audio upload — mirrors upload_image. ComfyUI's /upload/image endpoint
// (and the input/ directory) accept arbitrary media, which video/audio loader
// nodes (e.g. VHS_LoadVideo, LoadAudio) then read by filename.
// ---------------------------------------------------------------------------

const VIDEO_MIME: Record<string, string> = {
  ".mp4": "video/mp4",
  ".mov": "video/quicktime",
  ".webm": "video/webm",
  ".avi": "video/x-msvideo",
  ".mkv": "video/x-matroska",
  ".m4v": "video/x-m4v",
};

const AUDIO_MIME: Record<string, string> = {
  ".wav": "audio/wav",
  ".mp3": "audio/mpeg",
  ".flac": "audio/flac",
  ".ogg": "audio/ogg",
  ".m4a": "audio/mp4",
  ".aac": "audio/aac",
};

function resolveMediaMime(
  filename: string,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): string {
  const ext = extname(filename).toLowerCase();
  const mime = mimeMap[ext];
  if (!mime) {
    throw new ValidationError(
      `Unsupported ${kind} format "${ext}". Supported: ${Object.keys(mimeMap).join(", ")}`,
    );
  }
  return mime;
}

/** HTTP multipart upload of a media file to ComfyUI's input/ (works remotely). */
async function uploadMediaHttp(
  sourcePath: string,
  filename: string | undefined,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): Promise<{ filename: string }> {
  const resolvedFilename = filename ?? basename(sourcePath);
  const mimeType = resolveMediaMime(resolvedFilename, mimeMap, kind);
  const data = await nodeReadFile(sourcePath);
  logger.info(`Uploading ${kind} to ComfyUI via HTTP`, { sourcePath, resolvedFilename });
  const result = await uploadImageHttp(resolvedFilename, data, mimeType);
  return { filename: result.name };
}

/** Local filesystem copy of a media file into ComfyUI's input/ (needs COMFYUI_PATH). */
async function uploadMediaLocal(
  sourcePath: string,
  filename: string | undefined,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): Promise<{ filename: string; path: string }> {
  const inputDir = getInputDir();
  const resolvedFilename = filename ?? basename(sourcePath);
  resolveMediaMime(resolvedFilename, mimeMap, kind);
  const targetPath = join(inputDir, resolvedFilename);
  logger.info(`Uploading ${kind} to ComfyUI input`, { sourcePath, targetPath });
  try {
    await copyFile(sourcePath, targetPath);
  } catch (err) {
    throw new ValidationError(
      `Failed to copy ${kind}: ${err instanceof Error ? err.message : err}`,
    );
  }
  return { filename: resolvedFilename, path: targetPath };
}

export const uploadVideoAuto = (sourcePath: string, filename?: string) =>
  uploadMediaHttp(sourcePath, filename, VIDEO_MIME, "video");
export const uploadVideoLocal = (sourcePath: string, filename?: string) =>
  uploadMediaLocal(sourcePath, filename, VIDEO_MIME, "video");
export const uploadAudioAuto = (sourcePath: string, filename?: string) =>
  uploadMediaHttp(sourcePath, filename, AUDIO_MIME, "audio");
export const uploadAudioLocal = (sourcePath: string, filename?: string) =>
  uploadMediaLocal(sourcePath, filename, AUDIO_MIME, "audio");
