#!/usr/bin/env bash
set -euo pipefail
# ===== Auto-generated by scripts/gen-pack-installers.mjs — do not edit =====
# Pack: ERNIE-Image — Text to Image  (Linux / RunPod)
# Run from your ComfyUI root (the folder containing custom_nodes/ and models/).
[ -d custom_nodes ] || { echo "[ERROR] run from your ComfyUI root (custom_nodes/ not found)"; exit 1; }
PY="${PYTHON:-python3}"

clone() { # folder url
  if [ ! -d "custom_nodes/$1" ]; then
    echo "  cloning $1"; git clone --depth 1 "$2" "custom_nodes/$1"
    if [ -f "custom_nodes/$1/requirements.txt" ]; then echo "  installing $1 requirements.txt"; "$PY" -m pip install -r "custom_nodes/$1/requirements.txt"; fi
  else echo "  $1 present - skip"; fi
}
grab() { # relpath url
  mkdir -p "$(dirname "$1")"
  if [ ! -f "$1" ]; then echo "  downloading $(basename "$1")"; curl -L -o "$1" "$2"; else echo "  $(basename "$1") present - skip"; fi
}

echo "-------- custom nodes --------"
clone "ComfyUI-Manager" "https://github.com/ltdrdata/ComfyUI-Manager.git"
clone "ComfyUI-GGUF" "https://github.com/city96/ComfyUI-GGUF"
clone "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy"
clone "ComfyUI-Easy-Use" "https://github.com/yolain/ComfyUI-Easy-Use"
clone "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes"
clone "ComfyUI_essentials" "https://github.com/cubiq/ComfyUI_essentials"
clone "wlsh_nodes" "https://github.com/wallish77/wlsh_nodes"
clone "comfyui-vrgamedevgirl" "https://github.com/vrgamegirl19/comfyui-vrgamedevgirl"
clone "RES4LYF" "https://github.com/ClownsharkBatwing/RES4LYF"

echo "-------- pip (manifest extras) --------"
"$PY" -m pip install "librosa"

echo "-------- models --------"
grab "models/unet/ernie-image-turbo-Q8_0.gguf" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/ernie-image-turbo-Q8_0.gguf"
grab "models/text_encoders/ministral-3-3b.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/ministral-3-3b.safetensors"
grab "models/text_encoders/ernie-image-prompt-enhancer.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/ernie-image-prompt-enhancer.safetensors"
grab "models/vae/flux2-vae.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/flux2-vae.safetensors"

echo "DONE. Restart ComfyUI, then load workflow.json."
