#!/usr/bin/env bash
set -euo pipefail
# ===== Auto-generated by scripts/gen-pack-installers.mjs — do not edit =====
# Pack: Qwen-Image-Edit  (Linux / RunPod)
# Run from your ComfyUI root (the folder containing custom_nodes/ and models/).
[ -d custom_nodes ] || { echo "[ERROR] run from your ComfyUI root (custom_nodes/ not found)"; exit 1; }
PY="${PYTHON:-python3}"

clone() { # folder url
  if [ ! -d "custom_nodes/$1" ]; then
    echo "  cloning $1"; git clone --depth 1 "$2" "custom_nodes/$1"
    if [ -f "custom_nodes/$1/requirements.txt" ]; then echo "  installing $1 requirements.txt"; "$PY" -m pip install -r "custom_nodes/$1/requirements.txt"; fi
  else echo "  $1 present - skip"; fi
}
grab() { # relpath url
  mkdir -p "$(dirname "$1")"
  if [ ! -f "$1" ]; then echo "  downloading $(basename "$1")"; curl -L -o "$1" "$2"; else echo "  $(basename "$1") present - skip"; fi
}

echo "-------- custom nodes --------"
clone "ComfyUI-Manager" "https://github.com/ltdrdata/ComfyUI-Manager.git"
clone "ComfyUI-GGUF" "https://github.com/city96/ComfyUI-GGUF"
clone "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy"
clone "ComfyUI-Easy-Use" "https://github.com/yolain/ComfyUI-Easy-Use"
clone "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes"
clone "ComfyUI_UltimateSDUpscale" "https://github.com/ssitu/ComfyUI_UltimateSDUpscale"
clone "ComfyUI_essentials" "https://github.com/cubiq/ComfyUI_essentials"
clone "wlsh_nodes" "https://github.com/wallish77/wlsh_nodes"
clone "comfyui-vrgamedevgirl" "https://github.com/vrgamegirl19/comfyui-vrgamedevgirl"
clone "RES4LYF" "https://github.com/ClownsharkBatwing/RES4LYF"
clone "ComfyUI-Crystools" "https://github.com/crystian/ComfyUI-Crystools"

echo "-------- models --------"
grab "models/unet/Qwen_Image_Edit-Q8_0.gguf" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Qwen_Image_Edit-Q8_0.gguf"
grab "models/text_encoders/Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf"
grab "models/text_encoders/Qwen2.5-VL-7B-Instruct-UD-Q8_0.gguf" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Qwen2.5-VL-7B-Instruct-UD-Q8_0.gguf"
grab "models/vae/qwen_image_vae.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/qwen_image_vae.safetensors"
grab "models/loras/Qwen-Image-Lightning-4steps-V1.0.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Qwen-Image-Lightning-4steps-V1.0.safetensors"
grab "models/loras/Qwen-Image-Lightning-8steps-V1.1.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Qwen-Image-Lightning-8steps-V1.1.safetensors"
grab "models/upscale_models/4x-ClearRealityV1.pth" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/4x-ClearRealityV1.pth"
grab "models/upscale_models/RealESRGAN_x4plus_anime_6B.pth" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/RealESRGAN_x4plus_anime_6B.pth"

echo "DONE. Restart ComfyUI, then load workflow.json."
