@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
rem ===== Auto-generated by scripts/gen-pack-installers.mjs — do not edit =====
rem Pack: Z-Image-Turbo — ControlNet (Pose / Depth / Canny)
rem Run from your ComfyUI root (the folder containing custom_nodes\ and models\).
if not exist "custom_nodes" ( echo [ERROR] Run from your ComfyUI root ^(custom_nodes\ not found^). & pause & exit /b 1 )
where git >nul 2>&1 || ( echo [ERROR] git not found in PATH. & pause & exit /b 1 )
where curl >nul 2>&1 || ( echo [ERROR] curl not found in PATH. & pause & exit /b 1 )
set "PY=%CD%\..\python_embeded\python.exe"
if not exist "%PY%" set "PY=python"

echo -------- custom nodes --------
call :clone "ComfyUI-Manager" "https://github.com/ltdrdata/ComfyUI-Manager.git"
call :clone "ComfyUI-GGUF" "https://github.com/city96/ComfyUI-GGUF"
call :clone "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy"
call :clone "ComfyUI-Easy-Use" "https://github.com/yolain/ComfyUI-Easy-Use"
call :clone "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes"
call :clone "ComfyUI_UltimateSDUpscale" "https://github.com/ssitu/ComfyUI_UltimateSDUpscale"
call :clone "ComfyUI_essentials" "https://github.com/cubiq/ComfyUI_essentials"
call :clone "wlsh_nodes" "https://github.com/wallish77/wlsh_nodes"
call :clone "comfyui-vrgamedevgirl" "https://github.com/vrgamegirl19/comfyui-vrgamedevgirl"
call :clone "RES4LYF" "https://github.com/ClownsharkBatwing/RES4LYF"
call :clone "SeedVarianceEnhancer" "https://github.com/ChangeTheConstants/SeedVarianceEnhancer"
call :clone "ComfyUI-Detail-Daemon" "https://github.com/Jonseed/ComfyUI-Detail-Daemon"
call :clone "comfyui_controlnet_aux" "https://github.com/Fannovel16/comfyui_controlnet_aux"

echo -------- pip (manifest extras) --------
"%PY%" -m pip install "librosa"
"%PY%" -m pip install "scikit-image"

echo -------- models --------
call :grab "models\unet\z_image_turbo-Q8_0.gguf" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/z_image_turbo-Q8_0.gguf"
call :grab "models\text_encoders\Qwen3-4B-UD-Q6_K_XL.gguf" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Qwen3-4B-UD-Q6_K_XL.gguf"
call :grab "models\vae\z-image-ae.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/ae.safetensors"
call :grab "models\model_patches\Z-Image-Turbo-Fun-Controlnet-Union-fp8-e5m2.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Z-Image-Turbo-Fun-Controlnet-Union-fp8-e5m2.safetensors"

echo DONE. Restart ComfyUI, then load workflow.json.
pause
exit /b

:clone
if not exist "custom_nodes\%~1" (
  echo   cloning %~1
  git clone --depth 1 "%~2" "custom_nodes\%~1"
  if exist "custom_nodes\%~1\requirements.txt" ( echo   installing %~1 requirements.txt & "%PY%" -m pip install -r "custom_nodes\%~1\requirements.txt" )
) else ( echo   %~1 present - skip )
goto :eof

:grab
if not exist "%~dp1" mkdir "%~dp1"
if not exist "%~1" ( echo   downloading %~nx1 & curl -L --ssl-no-revoke -o "%~1" "%~2" ) else ( echo   %~nx1 present - skip )
goto :eof
