#!/usr/bin/env bash
set -euo pipefail
# ===== Auto-generated by scripts/gen-pack-installers.mjs — do not edit =====
# Pack: WAN Animate 2.2 — Character Replace (standalone)  (Linux / RunPod)
# Run from your ComfyUI root (the folder containing custom_nodes/ and models/).
[ -d custom_nodes ] || { echo "[ERROR] run from your ComfyUI root (custom_nodes/ not found)"; exit 1; }
PY="${PYTHON:-python3}"

clone() { # folder url
  if [ ! -d "custom_nodes/$1" ]; then
    echo "  cloning $1"; git clone --depth 1 "$2" "custom_nodes/$1"
    if [ -f "custom_nodes/$1/requirements.txt" ]; then echo "  installing $1 requirements.txt"; "$PY" -m pip install -r "custom_nodes/$1/requirements.txt"; fi
  else echo "  $1 present - skip"; fi
}
grab() { # relpath url
  mkdir -p "$(dirname "$1")"
  if [ ! -f "$1" ]; then echo "  downloading $(basename "$1")"; curl -L -o "$1" "$2"; else echo "  $(basename "$1") present - skip"; fi
}

echo "-------- custom nodes --------"
clone "ComfyUI-Manager" "https://github.com/ltdrdata/ComfyUI-Manager.git"
clone "ComfyUI-WanVideoWrapper" "https://github.com/kijai/ComfyUI-WanVideoWrapper"
clone "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy"
clone "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes"
clone "ComfyUI-VideoHelperSuite" "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
clone "ComfyUI-segment-anything-2" "https://github.com/kijai/ComfyUI-segment-anything-2"
clone "Comfyui-SecNodes" "https://github.com/9nate-drake/Comfyui-SecNodes"
clone "ComfyUI-WanAnimatePreprocess" "https://github.com/kijai/ComfyUI-WanAnimatePreprocess"

echo "-------- models --------"
grab "models/diffusion_models/Wan2_2-Animate-14B_fp8_scaled_e4m3fn_KJ_v2.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Wan2_2-Animate-14B_fp8_scaled_e4m3fn_KJ_v2.safetensors?download=true"
grab "models/text_encoders/umt5-xxl-enc-bf16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/umt5-xxl-enc-bf16.safetensors?download=true"
grab "models/vae/Wan2_1_VAE_bf16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Wan2_1_VAE_bf16.safetensors?download=true"
grab "models/clip_vision/clip_vision_h.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/clip_vision_h.safetensors?download=true"
grab "models/loras/WanAnimate_relight_lora_fp16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/WanAnimate_relight_lora_fp16.safetensors?download=true"
grab "models/loras/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors?download=true"
grab "models/sams/SeC-4B-fp16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/SeC-4B-fp16.safetensors?download=true"
grab "models/detection/vitpose-l-wholebody.onnx" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/vitpose-l-wholebody.onnx?download=true"
grab "models/detection/yolov10m.onnx" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/yolov10m.onnx?download=true"

echo "DONE. Restart ComfyUI, then load workflow.json."
