@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
rem ===== Auto-generated by scripts/gen-pack-installers.mjs — do not edit =====
rem Pack: WAN Animate 2.2 (v2v character replace)
rem Run from your ComfyUI root (the folder containing custom_nodes\ and models\).
if not exist "custom_nodes" ( echo [ERROR] Run from your ComfyUI root ^(custom_nodes\ not found^). & pause & exit /b 1 )
where git >nul 2>&1 || ( echo [ERROR] git not found in PATH. & pause & exit /b 1 )
where curl >nul 2>&1 || ( echo [ERROR] curl not found in PATH. & pause & exit /b 1 )
set "PY=%CD%\..\python_embeded\python.exe"
if not exist "%PY%" set "PY=python"

echo -------- custom nodes --------
call :clone "ComfyUI-Manager" "https://github.com/ltdrdata/ComfyUI-Manager.git"
call :clone "ComfyUI-WanVideoWrapper" "https://github.com/kijai/ComfyUI-WanVideoWrapper"
call :clone "rgthree-comfy" "https://github.com/rgthree/rgthree-comfy"
call :clone "ComfyUI-KJNodes" "https://github.com/kijai/ComfyUI-KJNodes"
call :clone "ComfyUI-VideoHelperSuite" "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
call :clone "ComfyUI-segment-anything-2" "https://github.com/kijai/ComfyUI-segment-anything-2"
call :clone "Comfyui-SecNodes" "https://github.com/9nate-drake/Comfyui-SecNodes"
call :clone "ComfyUI-WanAnimatePreprocess" "https://github.com/kijai/ComfyUI-WanAnimatePreprocess"

echo -------- models --------
call :grab "models\diffusion_models\Wan2_2-Animate-14B_fp8_scaled_e4m3fn_KJ_v2.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Wan2_2-Animate-14B_fp8_scaled_e4m3fn_KJ_v2.safetensors?download=true"
call :grab "models\text_encoders\umt5-xxl-enc-bf16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/umt5-xxl-enc-bf16.safetensors?download=true"
call :grab "models\vae\Wan2_1_VAE_bf16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/Wan2_1_VAE_bf16.safetensors?download=true"
call :grab "models\clip_vision\clip_vision_h.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/clip_vision_h.safetensors?download=true"
call :grab "models\loras\WanAnimate_relight_lora_fp16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/WanAnimate_relight_lora_fp16.safetensors?download=true"
call :grab "models\loras\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors?download=true"
call :grab "models\sams\SeC-4B-fp16.safetensors" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/SeC-4B-fp16.safetensors?download=true"
call :grab "models\detection\vitpose-l-wholebody.onnx" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/vitpose-l-wholebody.onnx?download=true"
call :grab "models\detection\yolov10m.onnx" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/yolov10m.onnx?download=true"
call :grab "models\detection\vitpose_h_wholebody_model.onnx" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/vitpose_h_wholebody_model.onnx?download=true"
call :grab "models\detection\vitpose_h_wholebody_data.bin" "https://huggingface.co/Aitrepreneur/FLX/resolve/main/vitpose_h_wholebody_data.bin?download=true"

echo DONE. Restart ComfyUI, then load workflow.json.
pause
exit /b

:clone
if not exist "custom_nodes\%~1" (
  echo   cloning %~1
  git clone --depth 1 "%~2" "custom_nodes\%~1"
  if exist "custom_nodes\%~1\requirements.txt" ( echo   installing %~1 requirements.txt & "%PY%" -m pip install -r "custom_nodes\%~1\requirements.txt" )
) else ( echo   %~1 present - skip )
goto :eof

:grab
if not exist "%~dp1" mkdir "%~dp1"
if not exist "%~1" ( echo   downloading %~nx1 & curl -L --ssl-no-revoke -o "%~1" "%~2" ) else ( echo   %~nx1 present - skip )
goto :eof
